#!/usr/bin/env python
#Example B5: smtplib
#Python Crash Course
#dzul.aiman@gmail.com
#2015/12/08

import smtplib

sender = 'XXX@nuclearmalaysia.gov.my'
password = 'yourpassword'
receivers = ['YYY@nuclearmalaysia.gov.my','ZZZ@nuclearmalaysia.gov.my']


message = """From: From Person <from@fromdomain.com>
To: To Person <to@todomain.com>
Subject: SMTP e-mail test

This is a test e-mail message.
"""

try:
    smtpserver = smtplib.SMTP("smtp.gmail.com",587)
    smtpserver.ehlo()
    smtpserver.starttls()
    smtpserver.ehlo
    smtpserver.login(sender, password)
    ssmtpserver.sendmail(sender, receivers, message)         
    print "Successfully sent email"
    smtpserver.close()
except SMTPException:
    print "Error: unable to send email"
